version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${pharmacy_user}
      POSTGRES_PASSWORD: ${1234}
      POSTGRES_DB: ${pharmacy}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

volumes:
  db_data: